### ISSUE TITLE
RSICD datasets

### ISSUE THREAD

**Issue by tiantianbukuaile** [comrados/noisy_captions#1]
The download link for the RSICD dataset has expired, can you provide the latest download link, I have been trying to reproduce the paper recently, thank you very much!Looking forward to hearing from you.

**Comment by comrados** [comment]
Hi

I no longer have access to that storage. Unfortunately I don't keep this information anywhere else.

You can generate your own data using scripts from [https://github.com/comrados/uhnd](https://github.com/comrados/uhnd)
images_embed.py
images_augment.py
captions_embed.py
captions_augment.py
captions_add_noise.py

**Comment by tiantianbukuaile** [comment]
Thank you for your reply
